title = "Credentials configuration file"

[person]
name = "Joy Mahapatra"
created = 2025-01-24T00:00:00Z

[huggingface]
token = ""

[github]
token = ""

[google]
token = "None"

[openai]
token = "None"